POST {{host}}/tracks
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "The Three Hunters",
    "movie_id": "b6c9d5ae-bf3b-419e-ba8f-09c8ce39d9bc"
}