// Code generated by mockery v2.53.4. DO NOT EDIT.

package storagemocks

import (
	context "context"

	domain "github.com/AlexFJ498/middle-earth-leitmotifs-api/internal"
	mock "github.com/stretchr/testify/mock"
)

// MovieRepository is an autogenerated mock type for the MovieRepository type
type MovieRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MovieRepository) Delete(ctx context.Context, id domain.MovieID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MovieID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, id
func (_m *MovieRepository) Find(ctx context.Context, id domain.MovieID) (domain.Movie, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MovieID) (domain.Movie, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.MovieID) domain.Movie); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Movie)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.MovieID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx
func (_m *MovieRepository) FindAll(ctx context.Context) ([]domain.Movie, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Movie, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Movie); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, movie
func (_m *MovieRepository) Save(ctx context.Context, movie domain.Movie) error {
	ret := _m.Called(ctx, movie)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Movie) error); ok {
		r0 = rf(ctx, movie)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, movie
func (_m *MovieRepository) Update(ctx context.Context, movie domain.Movie) error {
	ret := _m.Called(ctx, movie)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Movie) error); ok {
		r0 = rf(ctx, movie)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMovieRepository creates a new instance of MovieRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMovieRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MovieRepository {
	mock := &MovieRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
