// Code generated by mockery v2.53.4. DO NOT EDIT.

package storagemocks

import (
	context "context"

	domain "github.com/AlexFJ498/middle-earth-leitmotifs-api/internal"
	mock "github.com/stretchr/testify/mock"
)

// ThemeRepository is an autogenerated mock type for the ThemeRepository type
type ThemeRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ThemeRepository) Delete(ctx context.Context, id domain.ThemeID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ThemeID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, id
func (_m *ThemeRepository) Find(ctx context.Context, id domain.ThemeID) (domain.Theme, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Theme
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ThemeID) (domain.Theme, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ThemeID) domain.Theme); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Theme)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ThemeID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx
func (_m *ThemeRepository) FindAll(ctx context.Context) ([]domain.Theme, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Theme
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Theme, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Theme); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Theme)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, theme
func (_m *ThemeRepository) Save(ctx context.Context, theme domain.Theme) error {
	ret := _m.Called(ctx, theme)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Theme) error); ok {
		r0 = rf(ctx, theme)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, theme
func (_m *ThemeRepository) Update(ctx context.Context, theme domain.Theme) error {
	ret := _m.Called(ctx, theme)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Theme) error); ok {
		r0 = rf(ctx, theme)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewThemeRepository creates a new instance of ThemeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewThemeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ThemeRepository {
	mock := &ThemeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
