// Code generated by mockery v2.53.4. DO NOT EDIT.

package storagemocks

import (
	context "context"

	domain "github.com/AlexFJ498/middle-earth-leitmotifs-api/internal"
	mock "github.com/stretchr/testify/mock"
)

// TrackThemeRepository is an autogenerated mock type for the TrackThemeRepository type
type TrackThemeRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, trackID, themeID, startSecond
func (_m *TrackThemeRepository) Delete(ctx context.Context, trackID domain.TrackID, themeID domain.ThemeID, startSecond domain.StartSecond) error {
	ret := _m.Called(ctx, trackID, themeID, startSecond)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TrackID, domain.ThemeID, domain.StartSecond) error); ok {
		r0 = rf(ctx, trackID, themeID, startSecond)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, trackID, themeID, startSecond
func (_m *TrackThemeRepository) Find(ctx context.Context, trackID domain.TrackID, themeID domain.ThemeID, startSecond domain.StartSecond) (domain.TrackTheme, error) {
	ret := _m.Called(ctx, trackID, themeID, startSecond)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.TrackTheme
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TrackID, domain.ThemeID, domain.StartSecond) (domain.TrackTheme, error)); ok {
		return rf(ctx, trackID, themeID, startSecond)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TrackID, domain.ThemeID, domain.StartSecond) domain.TrackTheme); ok {
		r0 = rf(ctx, trackID, themeID, startSecond)
	} else {
		r0 = ret.Get(0).(domain.TrackTheme)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TrackID, domain.ThemeID, domain.StartSecond) error); ok {
		r1 = rf(ctx, trackID, themeID, startSecond)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByTrack provides a mock function with given fields: ctx, trackID
func (_m *TrackThemeRepository) FindByTrack(ctx context.Context, trackID domain.TrackID) ([]domain.TrackTheme, error) {
	ret := _m.Called(ctx, trackID)

	if len(ret) == 0 {
		panic("no return value specified for FindByTrack")
	}

	var r0 []domain.TrackTheme
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TrackID) ([]domain.TrackTheme, error)); ok {
		return rf(ctx, trackID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TrackID) []domain.TrackTheme); ok {
		r0 = rf(ctx, trackID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TrackTheme)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TrackID) error); ok {
		r1 = rf(ctx, trackID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, trackTheme
func (_m *TrackThemeRepository) Save(ctx context.Context, trackTheme domain.TrackTheme) error {
	ret := _m.Called(ctx, trackTheme)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TrackTheme) error); ok {
		r0 = rf(ctx, trackTheme)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, trackTheme
func (_m *TrackThemeRepository) Update(ctx context.Context, trackTheme domain.TrackTheme) error {
	ret := _m.Called(ctx, trackTheme)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TrackTheme) error); ok {
		r0 = rf(ctx, trackTheme)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTrackThemeRepository creates a new instance of TrackThemeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrackThemeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrackThemeRepository {
	mock := &TrackThemeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
