// Code generated by mockery v2.53.4. DO NOT EDIT.

package storagemocks

import (
	context "context"

	domain "github.com/AlexFJ498/middle-earth-leitmotifs-api/internal"
	mock "github.com/stretchr/testify/mock"
)

// TrackRepository is an autogenerated mock type for the TrackRepository type
type TrackRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *TrackRepository) Delete(ctx context.Context, id domain.TrackID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TrackID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, id
func (_m *TrackRepository) Find(ctx context.Context, id domain.TrackID) (domain.Track, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Track
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TrackID) (domain.Track, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TrackID) domain.Track); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Track)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TrackID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx
func (_m *TrackRepository) FindAll(ctx context.Context) ([]domain.Track, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Track
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Track, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Track); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Track)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, track
func (_m *TrackRepository) Save(ctx context.Context, track domain.Track) error {
	ret := _m.Called(ctx, track)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Track) error); ok {
		r0 = rf(ctx, track)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, track
func (_m *TrackRepository) Update(ctx context.Context, track domain.Track) error {
	ret := _m.Called(ctx, track)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Track) error); ok {
		r0 = rf(ctx, track)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTrackRepository creates a new instance of TrackRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrackRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrackRepository {
	mock := &TrackRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
