POST {{host}}/groups
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Rohan",
    "description": "The land of the horse-lords",
    "image_url": "/groups/rohan.jpg"
}